// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PriorityTask.API.Migrations
{
    [DbContext(typeof(PriorityTaskAPIContext))]
    partial class PriorityTaskAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriorityTask.Modelos.Materia", b =>
                {
                    b.Property<int>("idMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_materia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idMateria"));

                    b.Property<string>("codigoColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_color");

                    b.Property<string>("docente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("docente");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("idMateria");

                    b.HasIndex("idUsuario");

                    b.ToTable("materias");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Nota", b =>
                {
                    b.Property<int>("idNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_nota");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idNota"));

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("idMateria")
                        .HasColumnType("integer")
                        .HasColumnName("id_materia");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("idNota");

                    b.HasIndex("idMateria");

                    b.ToTable("notas");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Subtarea", b =>
                {
                    b.Property<int>("idSubtarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Subtareas");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idSubtarea"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("esCompletada")
                        .HasColumnType("boolean")
                        .HasColumnName("completada");

                    b.Property<int>("id_tarea")
                        .HasColumnType("integer")
                        .HasColumnName("id_tarea");

                    b.HasKey("idSubtarea");

                    b.HasIndex("id_tarea");

                    b.ToTable("subtareas");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Tarea", b =>
                {
                    b.Property<int>("idTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tarea");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTarea"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("fechaLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_limite");

                    b.Property<int>("idMateria")
                        .HasColumnType("integer")
                        .HasColumnName("id_materia");

                    b.Property<int>("prioridad")
                        .HasColumnType("integer")
                        .HasColumnName("prioridad");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("idTarea");

                    b.HasIndex("idMateria");

                    b.ToTable("tareas");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Materia", b =>
                {
                    b.HasOne("PriorityTask.Modelos.Usuario", "usuario")
                        .WithMany("materias")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Nota", b =>
                {
                    b.HasOne("PriorityTask.Modelos.Materia", "materia")
                        .WithMany("notas")
                        .HasForeignKey("idMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("materia");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Subtarea", b =>
                {
                    b.HasOne("PriorityTask.Modelos.Tarea", "tarea")
                        .WithMany("subtareas")
                        .HasForeignKey("id_tarea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tarea");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Tarea", b =>
                {
                    b.HasOne("PriorityTask.Modelos.Materia", "materia")
                        .WithMany("tareas")
                        .HasForeignKey("idMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("materia");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Materia", b =>
                {
                    b.Navigation("notas");

                    b.Navigation("tareas");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Tarea", b =>
                {
                    b.Navigation("subtareas");
                });

            modelBuilder.Entity("PriorityTask.Modelos.Usuario", b =>
                {
                    b.Navigation("materias");
                });
#pragma warning restore 612, 618
        }
    }
}
